spring.application.name=congresso
server.port=8000

# Configurazione Database H2 su File Persistente
spring.datasource.url=jdbc:h2:file:./data/congresso_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Gestione Schema DDL
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# H2 Console per debug locale
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console